<a href="https://colab.research.google.com/github/zyf-hitsz/PytorchLearning/blob/main/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C/%E7%BA%BF%E6%80%A7%E5%B1%82/LinearLayers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#线性层LinearLayers


### 线性层的主要作用

1. **特征提取与转换**：线性层通过学习权重矩阵 $W$ 和偏置 $b$，将输入向量转换到另一个空间。这有助于模型学习特征之间的复杂关系。
2. **维度调整**：在神经网络架构中，我们经常需要改变张量的形状。例如，将卷积层的输出平铺后输入到线性层，最后通过线性层映射到分类的类别数量上。
3. **参数学习**：线性层包含可训练的参数（权重和偏置），反向传播算法会根据损失函数更新这些参数，以使模型更好地拟合数据。

严格意义上的线性层只进行线性计算，不包含激活函数，它的核心功能就是通过可学习的参数实现特征的线性变换与维度调整，

##线性层nn.Linear
**数学公式**：
$$y = xW^T + b$$
其中 $W$ 是权重，$b$ 是偏置。
严格来说，只要存在 $b$，这个运算实际上是仿射变换。

Linear把原来的若干个输入特征按照可训练的权重重新加权、组合，得到新的特征。

In [ ]:
class torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
#in_features：输入神经元的数量，对应输入张量最后一个维度的尺寸。
#out_features: 输出神经元的数量，决定了线性变换后输出张量的维度。
#bias:偏置，即b，默认为True
#Linaer只处理输入Tensor的最后一个维度，前面的维度都不会改变。

In [5]:
import torch
import torch.nn as nn

# 假设输入特征维度为 10，输出特征维度为 5
input_features = 10
output_features = 5

# 定义一个线性层
linear_layer = nn.Linear(in_features=input_features, out_features=output_features)

# 查看初始化的权重和偏置
print("Weight.Shape :", linear_layer.weight.shape)
print("Weight :", linear_layer.weight)
print("Bias.Shape :", linear_layer.bias.shape)
print("Bias :", linear_layer.bias)



# 创建一个随机输入张量 (batch_size=2, features=10)
x = torch.randn(2, 10)

# 前向传播
output = linear_layer(x)

print("\nInput:\n", x)
print("\nOutput (Linear transformation result):\n", output)

Weight.Shape : torch.Size([5, 10])
Weight : Parameter containing:
tensor([[-0.0690, -0.2524, -0.3013, -0.1989, -0.0997,  0.0672,  0.1033, -0.2040,
          0.2942, -0.0304],
        [-0.3110,  0.1702,  0.0682, -0.3018,  0.0127,  0.2902, -0.1341, -0.0386,
         -0.2238, -0.2631],
        [ 0.0965,  0.0098, -0.0762,  0.2865, -0.0150, -0.1677,  0.2581,  0.1482,
         -0.3069, -0.3122],
        [ 0.1236, -0.1571, -0.3150, -0.2621, -0.2022, -0.2457, -0.0417,  0.1774,
          0.2527, -0.2570],
        [-0.0028,  0.0519,  0.1606, -0.2510, -0.1150,  0.0806, -0.1157, -0.1659,
         -0.0707,  0.0737]], requires_grad=True)
Bias.Shape : torch.Size([5])
Bias : Parameter containing:
tensor([-0.0214, -0.1720,  0.0754,  0.0941,  0.0237], requires_grad=True)

Input:
 tensor([[-0.7841, -1.1927,  1.1740,  0.2285,  0.2914, -0.7485, -1.4487, -0.6416,
         -0.2297,  0.3475],
        [ 0.6126,  0.4393,  1.7087, -1.4573,  0.2776,  0.9482,  1.8044, -1.2611,
          0.1281,  0.4275]])

Output 

上面这个例子里面，输入维度为10，输出维度为5，即linear = nn.Linear(10, 5)，但是权重的规模却是[5,10]，输入输出维度是相反的，这是矩阵计算的性质天然决定的，偏执的维度为5和输出维度相同，那么总参数就是：

$$\boxed{
N_{\text{param}}
=
\text{in_features}\times\text{out_features}
+\text{out_features}
}$$
需要注意。
Linear 可以升维，也可以降维，可以认为是任意维度之间的可学习映射。在CNN,Transformer等现代神经网络架构中应用非常广泛，起到最终特征整合、分类等作用。




##Identity--“什么都不做层”


In [ ]:
class torch.nn.Identity()

nn.Identity()在神经网络中没有任何数学内容，它只进行一个操作，$y=x$。主要作用是为了方便设计可配置的神经网络结构，例如：


```
if use_dropout:
    self.dropout = nn.Dropout(0.5)
else:
    self.dropout = nn.Identity()
```
那么前向计算式可以统一写成


```
x = self.dropout(x)
```
不需要再用if语句分类操作。



##Bilinear双线性层
Bilinear 有两个输入：

$$x_1,x_2$$
计算：

$$y=x_1^TAx_2+b$$
Bilinear更能直接描述两个输入特征之间的乘性关系。



In [ ]:
class torch.nn.Bilinear(in1_features, in2_features, out_features, bias=True, device=None, dtype=None)
#要求确定两个输入的维度和一个输出的维度，一共三个参数

##Lazylinear--自动推断输入维度的Linear


```
class torch.nn.LazyLinear(out_features, bias=True, device=None, dtype=None)
```
实际计算和Linear是一模一样的，只是不需要指定输入维度，而是根据第一个输入的维度自动确定输入维度。



#全连接层Fully connected Layers
侠义的全连接层等价于线性层，用于形象地描述线性层输入的每一个神经元和输出的神经元之间紧密联系的放射计算的关系。部分地方将全连接层广义地理解为线性层和非线性激活等其他层之间的组合，将其理解为一个完整的全连接神经元模块。
